In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier

In [2]:
df=pd.read_csv("spam.csv")

In [3]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [5]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [6]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:

x_train,x_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [8]:
df.shape

(5572, 3)

In [9]:
x_train.shape

(4457,)

In [10]:
x_test.shape

(1115,)

In [11]:
type(x_train)

pandas.core.series.Series

In [12]:
x_train[:4]

4157    Yo, call me when you get the chance, a friend ...
1046                                   Come round, it's .
1916    Its not that time of the month nor mid of the ...
398     You are always putting your business out there...
Name: Message, dtype: object

In [13]:
 type(y_train)

pandas.core.series.Series

In [14]:
y_train[:4]

4157    0
1046    0
1916    0
398     0
Name: spam, dtype: int64

In [15]:
v=CountVectorizer()

In [16]:
x_train_cv=v.fit_transform(x_train.values)
x_train_cv

<4457x7808 sparse matrix of type '<class 'numpy.int64'>'
	with 59711 stored elements in Compressed Sparse Row format>

In [17]:
x_train_cv[0]

<1x7808 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [18]:
x_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [19]:
x_train_cv.shape

(4457, 7808)

In [20]:
v.get_feature_names_out()[1000:1050]

array(['ansr', 'answer', 'answered', 'answerin', 'answering', 'answers',
       'antelope', 'anthony', 'anti', 'antibiotic', 'any', 'anybody',
       'anyhow', 'anymore', 'anyone', 'anyones', 'anyplaces', 'anythiing',
       'anythin', 'anything', 'anythingtomorrow', 'anytime', 'anyway',
       'anyways', 'anywhere', 'aom', 'apart', 'apartment', 'apes',
       'apeshit', 'aphex', 'apnt', 'apo', 'apologetic', 'apologise',
       'apologize', 'apology', 'app', 'apparently', 'appeal', 'appendix',
       'applausestore', 'applebees', 'apples', 'application', 'apply',
       'applyed', 'appointment', 'appointments', 'appreciate'],
      dtype=object)

In [21]:
v.get_feature_names_out().shape

(7808,)

In [22]:
#dir(v)

In [23]:
v.vocabulary_

{'yo': 7761,
 'call': 1639,
 'me': 4460,
 'when': 7538,
 'you': 7766,
 'get': 3178,
 'the': 6879,
 'chance': 1750,
 'friend': 3062,
 'of': 4954,
 'mine': 4542,
 'wanted': 7439,
 'to': 6995,
 'ask': 1115,
 'about': 770,
 'big': 1370,
 'order': 5044,
 'come': 1940,
 'round': 5902,
 'it': 3814,
 'its': 3821,
 'not': 4890,
 'that': 6876,
 'time': 6962,
 'month': 4633,
 'nor': 4877,
 'mid': 4522,
 'are': 1069,
 'always': 947,
 'putting': 5587,
 'your': 7772,
 'business': 1604,
 'out': 5072,
 'there': 6898,
 'put': 5584,
 'pictures': 5275,
 'ass': 1124,
 'on': 4994,
 'facebook': 2793,
 'one': 5000,
 'most': 4649,
 'open': 5018,
 'people': 5210,
 've': 7320,
 'ever': 2711,
 'met': 4515,
 'why': 7562,
 'would': 7670,
 'think': 6913,
 'picture': 5274,
 'room': 5894,
 'hurt': 3614,
 'make': 4380,
 'feel': 2857,
 'violated': 7356,
 'don': 2446,
 'run': 5930,
 'away': 1188,
 'frm': 3069,
 'walk': 7421,
 'slowly': 6310,
 'amp': 966,
 'kills': 3992,
 'care': 1687,
 'enough': 2651,
 'stop': 6559,
 'i

In [24]:
v.get_feature_names_out()[5257]

'phone750'

In [25]:
x_train_np=x_train_cv.toarray()
x_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
x_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [27]:
np.where(x_train_np[0]!=0)

(array([ 770, 1115, 1370, 1639, 1750, 3062, 3178, 4460, 4542, 4954, 5044,
        6879, 6995, 7439, 7538, 7761, 7766], dtype=int64),)

In [28]:
x_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [29]:
model=MultinomialNB()

In [30]:
model.fit(x_train_cv,y_train)

MultinomialNB()

In [31]:
x_test_cv=v.transform(x_test)

In [32]:

y_pred=model.predict(x_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       964
           1       0.97      0.95      0.96       151

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [33]:
emails=[
    
    "Hey Mohan,can we get together to watch football game tomorrow?",
    "Upto 20% discount on parking, exclusive offer just for you.Dont miss this reward!"
]

In [34]:
emails_count=v.transform(emails)

In [35]:
model.predict(emails_count)

array([0, 1], dtype=int64)

In [36]:

clf=Pipeline([
    
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [37]:
clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [38]:
y_pred=clf.predict(x_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       964
           1       0.97      0.95      0.96       151

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [39]:
data=pd.read_csv("IMDB Dataset.csv")

In [40]:
data.shape

(50000, 2)

In [41]:
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [42]:
data['category']=data['sentiment'].apply(lambda x:1 if x=='positive' else 0)

In [43]:
data.head()

review sentiment  category
0  One of the other reviewers has mentioned that ...  positive         1
1  A wonderful little production. <br /><br />The...  positive         1
2  I thought this was a wonderful way to spend ti...  positive         1
3  Basically there's a family where a little boy ...  negative         0
4  Petter Mattei's "Love in the Time of Money" is...  positive         1

In [44]:
data.category.value_counts()

1    25000
0    25000
Name: category, dtype: int64

In [45]:
xtrain,xtest,ytrain,ytest=train_test_split(data.review,data.category,test_size=0.2)

In [46]:
RF_clf=Pipeline([
    
    ('vectorizer',CountVectorizer()),
    ('random_forrest',(RandomForestClassifier(n_estimators=50,criterion='entropy')))
])

RF_clf.fit(xtrain,ytrain)
ypred=RF_clf.predict(xtest)
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.83      0.84      0.84      5026
           1       0.84      0.83      0.83      4974

    accuracy                           0.84     10000
   macro avg       0.84      0.84      0.84     10000
weighted avg       0.84      0.84      0.84     10000

